// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3GcHeQfWcKoJmq9Io9bx4BloJBZycS8',
    appId: '1:322174025333:web:ebd857d1cca64c4906023c',
    messagingSenderId: '322174025333',
    projectId: 'devizpro-ultra-pilot',
    authDomain: 'devizpro-ultra-pilot.firebaseapp.com',
    storageBucket: 'devizpro-ultra-pilot.firebasestorage.app',
    measurementId: 'G-V81LL35R71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBySKgFjhHMTaIdkdI2LWJPDMAM-bu3aDc',
    appId: '1:322174025333:android:21fb6ce5f61ea74a06023c',
    messagingSenderId: '322174025333',
    projectId: 'devizpro-ultra-pilot',
    storageBucket: 'devizpro-ultra-pilot.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz3GcHeQfWcKoJmq9Io9bx4BloJBZycS8',
    appId: '1:322174025333:web:c09b2308cdd49a4906023c',
    messagingSenderId: '322174025333',
    projectId: 'devizpro-ultra-pilot',
    authDomain: 'devizpro-ultra-pilot.firebaseapp.com',
    storageBucket: 'devizpro-ultra-pilot.firebasestorage.app',
    measurementId: 'G-9PW62ZRBSK',
  );
}
